/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeeRouteImport } from './routes/tee'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BespokeRouteImport } from './routes/bespoke'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TeeRoute = TeeRouteImport.update({
  id: '/tee',
  path: '/tee',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BespokeRoute = BespokeRouteImport.update({
  id: '/bespoke',
  path: '/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tee': typeof TeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tee': typeof TeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bespoke': typeof BespokeRoute
  '/contact': typeof ContactRoute
  '/returns': typeof ReturnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tee': typeof TeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bespoke'
    | '/contact'
    | '/returns'
    | '/sitemap.xml'
    | '/tee'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bespoke'
    | '/contact'
    | '/returns'
    | '/sitemap.xml'
    | '/tee'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bespoke'
    | '/contact'
    | '/returns'
    | '/sitemap.xml'
    | '/tee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BespokeRoute: typeof BespokeRoute
  ContactRoute: typeof ContactRoute
  ReturnsRoute: typeof ReturnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeeRoute: typeof TeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tee': {
      id: '/tee'
      path: '/tee'
      fullPath: '/tee'
      preLoaderRoute: typeof TeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bespoke': {
      id: '/bespoke'
      path: '/bespoke'
      fullPath: '/bespoke'
      preLoaderRoute: typeof BespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BespokeRoute: BespokeRoute,
  ContactRoute: ContactRoute,
  ReturnsRoute: ReturnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeeRoute: TeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
